id: ACC3691C9
base_file: f7E35.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:04:11.133779
  last_modified_at: 2022-06-19 18:04:11.133786
