id: ACC3691C9
base_file: fA419.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:04:11.136303
  last_modified_at: 2022-06-19 18:04:11.136310
